CREATE DATABASE BDACADEMIA
GO
USE BDACADEMIA
GO
CREATE TABLE ALUNO
(
	CODALUNO		INT IDENTITY NOT NULL CONSTRAINT PKAluno PRIMARY KEY,
	NOME			VARCHAR(50) NOT NULL,
	CPF				CHAR (11) CONSTRAINT UQCPF UNIQUE NOT NULL,
	RG				VARCHAR(20),
	EMAIL			VARCHAR(50) NOT NULL,
	DATANASCIMENTO	DATE
)
GO

CREATE TABLE PLANO (
	CODPLANO	INT NOT NULL CONSTRAINT PKPlano PRIMARY KEY IDENTITY,
	NOMEPLANO	VARCHAR(50) NOT NULL,
	VALORPLANO	MONEY NOT NULL
)
GO

CREATE TABLE MATRICULA (
	CODMATRICULA	INT NOT NULL CONSTRAINT PKMatricula PRIMARY KEY IDENTITY,
	CODPLANO		INT CONSTRAINT FKPlano FOREIGN KEY REFERENCES PLANO (CODPLANO),
	CODALUNO		INT CONSTRAINT FKAluno FOREIGN KEY REFERENCES ALUNO (CODALUNO),
	DATAMATRICULA	DATE,
	DATAVENCIMENTO	DATE
)
GO

CREATE TABLE USUARIO (
	CODUSUARIO INT NOT NULL CONSTRAINT PKUsuario PRIMARY KEY IDENTITY,
	NOMEUSUARIO VARCHAR(30) NOT NULL CONSTRAINT UQUsuario UNIQUE,
	SENHA VARCHAR(15) NOT NULL,
	TIPOUSUARIO VARCHAR(20) NOT NULL
)
GO

